# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: data.json builder

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        ref: development

    - name: RUN PYTHON SCRIPT
      env:
        APIKEY_CSV2JSON: ${{ secrets.APIKEY_CSV2JSON }}
      run: |
        python3 -c "import os; os.chdir('.github/tools'); import make_data_json; x = make_data_json.process('$env:APIKEY_CSV2JSON'); print(x)" > data.json
        
        
    - name: COMMIT
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add data.json
        git commit -m "[BOT] Update data.json" || true
        git fetch origin development
        git merge
        
    - name: PUSH
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'development'
