# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - run: pip install requests
    - name: RUN PYTHON SCRIPT
      run: |
        python -c "import os; os.chdir('.github/tools'); import make_data_json; x = make_data_json.process(); print(x)" > data2.json
        
    - name: COMMIT
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data2.json
        git commit -m "[BOT] Update data2.json" || true
        git fetch origin dev-hamamatsu
        git merge
        
    - name: PUSH
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: 'development'
